version: "3.2"

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: googlesheets
      POSTGRES_USER: googlesheets
      POSTGRES_PASSWORD: googlesheets

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    restart: on-failure

volumes:
  postgres_data:
