version: "3.2"

services:
  web:
    image: "settings:dev"
    build:
      context: .
      cache_from:
        - "settings:dev"
        - "settings:latest"
        - "*"
      args:
        DJANGO_ENV: development
    command: python -Wd src/manage.py runserver 127.0.0.1:8000
    ports:
      - "8000:8000"
    env_file:
      - ./src/settings/.env
    depends_on:
      - db

  db:
    image: postgres:13
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: googlesheets
      POSTGRES_USER: googlesheets
      POSTGRES_PASSWORD: googlesheets

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    restart: on-failure

volumes:
  postgres_data:
