# Generated by Django 4.1 on 2022-08-11 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.IntegerField()),
                ('order', models.CharField(max_length=7)),
                ('price_in_dollars', models.IntegerField()),
                ('price_in_rubles', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-delivery_date'],
            },
        ),
    ]
