# Generated by Django 4.1 on 2022-08-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='change_date',
            new_name='changed_date',
        ),
    ]
