# Generated by Django 4.1 on 2022-08-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_from_file',
            field=models.BooleanField(default=True),
        ),
    ]
